version: "3.7"

services:
  web:
    build: ./
    ports:
      - "9009:9009"
    networks:
      - network
  postgres:
    image: "postgres:16.2"
    container_name: ${APP_NAME}-pg
    shm_size: 128mb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_USER: ${DB_ADMIN_LOGIN}
    networks:
      - network

networks:
  network:
    driver: bridge
